/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package datastructures;

public class Library {
   public static void main(String args[]) {
	   System.out.println("Hello World");
   }
}
